CREATE TABLE addresses
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    zip_code VARCHAR(255)                            NOT NULL,
    city     VARCHAR(255)                            NOT NULL,
    country  VARCHAR(255)                            NOT NULL,
    street   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000)                           NOT NULL,
    category_id  BIGINT                                  NOT NULL,
    venue_id     BIGINT                                  NOT NULL,
    start_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    image_path   VARCHAR(255),
    end_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_type   VARCHAR(255)                            NOT NULL,
    ticket_price DOUBLE PRECISION                        NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    created_by   VARCHAR(255),
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_by   VARCHAR(255),
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE registrations
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    event_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_registrations PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    event_id BIGINT                                  NOT NULL,
    comment  VARCHAR(1000),
    rating   INTEGER                                 NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (id)
);

CREATE TABLE tickets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    age        INTEGER                                 NOT NULL,
    roles      VARCHAR(255),
    address_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_by VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE venues
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    address_id BIGINT                                  NOT NULL,
    capacity   INTEGER                                 NOT NULL,
    CONSTRAINT pk_venues PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venues (id);

ALTER TABLE registrations
    ADD CONSTRAINT FK_REGISTRATIONS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE registrations
    ADD CONSTRAINT FK_REGISTRATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;

ALTER TABLE tickets
    ADD CONSTRAINT FK_TICKETS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);

ALTER TABLE venues
    ADD CONSTRAINT FK_VENUES_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES addresses (id);